# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.6
  - nightly
os:
  - linux
  - windows
  - osx
arch:
  - x64
cache:
  directories:
    - ~/.julia/artifacts
matrix:
  allow_failures:
    - julia: nightly
  exclude:
    - os: osx
      julia: nightly
    - os: windows
      julia: nightly
  fast_finish: true
branches:
  only:
    - main
    - /release-.*/
