name = "PPLM"
uuid = "80fe3cd3-18f3-43a0-bc53-22e3608ca67d"
authors = ["Adarsh Kumar"]
version = "0.1.0"

[deps]
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
