[legal]
git-tree-sha1 = "31910cb9bc5fd2026f64692a3ca1b062be78c937"
lazy = true

    [[legal.download]]
    sha256 = "b2ce6f2a382b16a73bf72dc765d3e8f88268767d"
    url = "https://s3.amazonaws.com/models.huggingface.co/bert/pplm/bow/legal.txt"

[military]
git-tree-sha1 = "df7a48a7780609d39e9cc9ceed6ac06019a884d7"
lazy = true

    [[military.download]]
    sha256 = "8454f8487e89163961a91be67b86d65e297faad6"
    url = "https://s3.amazonaws.com/models.huggingface.co/bert/pplm/bow/military.txt"

[monsters]
git-tree-sha1 = "d090ad6b9b74fcb4cd301ce8ccc847cf7cae4b04"
lazy = true

    [[monsters.download]]
    sha256 = "7bbdb23155fa0ea8e05162e8d67342b68c0b61c2"
    url = "https://s3.amazonaws.com/models.huggingface.co/bert/pplm/bow/monsters.txt"

[politics]
git-tree-sha1 = "b284d97ab281a42dadd3a3f958934051ae859c3d"
lazy = true

    [[politics.download]]
    sha256 = "858e41b5a7709752db7476deb51f52fe566b2a8f"
    url = "https://s3.amazonaws.com/models.huggingface.co/bert/pplm/bow/politics.txt"

[positive_words]
git-tree-sha1 = "e1002313a378f39215ac785cd82ef10d31c75383"
lazy = true

    [[positive_words.download]]
    sha256 = "6bfd075e8767011a5037f6820a0bdb5a2d748c95"
    url = "https://s3.amazonaws.com/models.huggingface.co/bert/pplm/bow/positive_words.txt"

[religion]
git-tree-sha1 = "39cac44d1ed3681afbf834f222397bd3e5f037ae"
lazy = true

    [[religion.download]]
    sha256 = "066a5d7b0ddd4f22af1fea838f45877fa5a9392d"
    url = "https://s3.amazonaws.com/models.huggingface.co/bert/pplm/bow/religion.txt"

[science]
git-tree-sha1 = "9ed5cd23f4eff0f76f72f87e2a5141bb2995365a"
lazy = true

    [[science.download]]
    sha256 = "6362f30eb8faf5987d5dbe2fd64802c399f8eb55"
    url = "https://s3.amazonaws.com/models.huggingface.co/bert/pplm/bow/science.txt"

[space]
git-tree-sha1 = "0aa7b97ed43f1ce20273091bdbb0ffc36b32c9b5"
lazy = true

    [[space.download]]
    sha256 = "ce4d466a6833dfb37434a9bc4cce52d299213585"
    url = "https://s3.amazonaws.com/models.huggingface.co/bert/pplm/bow/space.txt"

[technology]
git-tree-sha1 = "39704eed4a214ef01491695bd1405336d839b414"
lazy = true

    [[technology.download]]
    sha256 = "19077ac8944fc8eee2b03acfb27a977fdcd8cb62"
    url = "https://s3.amazonaws.com/models.huggingface.co/bert/pplm/bow/technology.txt"
